AWSTemplateFormatVersion: 2010-09-09
Description: >-
  

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  AppId:
    Type: String

Resources:
  s3JsonLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/s3-json-logger.pdfHandler
      Runtime: nodejs10.x
      Role: !Sub: 'arn:aws:iam::${AWS::AccountId}:role/new-cloud-nirda-s3JsonLoggerFunctionRole-7SFR3P8RIT7'
      Resource: "*"
      Description: A Lambda function that logs a json file sent to S3 bucket.
      MemorySize: 128
      Timeout: 60
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
      Events:
        simpleappbucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref simpleappbucket
            Events: s3:ObjectCreated:*
  simpleappbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
